name: Java CI

on:
  push:
    branches:
      - main  # Change this to the name of your default branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Change this to the Java version you're using
        
    - name: Compile Java
      run: javac -d . src/WeatherApp.java  # Adjust the compile command and source path
    
    - name: Run Tests
      run: java -cp . YourTestClassName  # Replace with the command to run your tests
